"""initial migration

Revision ID: 935fc11d12e4
Revises: 
Create Date: 2018-04-15 19:50:00.580942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '935fc11d12e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uri')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
